### ISSUE TITLE
Definere TopicAccess CRD

### ISSUE THREAD

**Issue by mortenlj** [navikt/nada-kafkarator#16]
Se #15.

Forslag:

```yaml
TopicAccess:
  topic:
    name: <topic>
    namespace: <namespace>
    owner: <owner team>
  granted:
    - <team1>
    - <team2>
  requested:
    - <team3>
    - <team4>
```
